######################################
#                                    #
#      SQLEconomy Configuration      #
#                                    #
######################################

# Set the default money your players will have. MUST BE A WHOLE NUMBER
DefaultMoney: 1000
# Unit (dollars, pounts, etc)
MoneyUnit: dollars
# Tax rate (percentage)
TaxRate: 0
# Server name
servername: Test
# EventTable
table: eventlog